# Site settings
title: WeChatPythonStudy
SEOTitle: Ours' Website
header-img: img/home-bg.jpg
email: wangzhui@foxmail.com
description: "Developer"
keyword: "keyword"
url: ""              # your host, for absolute URL
#baseurl: "/blog"                            				# for example, '/blog' if your blog hosted on 'host/blog'
#baseurlnext: "https://www.wangzhui.site/index.htm"                            				# for example, '/blog' if your blog hosted on 'host/blog'
nm: true
header-mask:  0.5

# SNS settings
RSS: false
weibo_username:     Python Study
zhihu_username:     none
github_username:    none
twitter_username:   none
#facebook_username:  MrLycorious
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
#paginate_path: "/blog/:num/"


# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: ["jekyll-paginate","jekyll-mermaid"]

mermaid:
    src: './js/mermaid.js'
    src_config: '/js/mermaid_config.js'



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: none

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: MrLycorious.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description:  "Description of"
sidebar-avatar: /img/shenzai.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`
sidebar-wechatgroup:  /img/wechatgroup.png


# Featured Tags
featured-book-tags: true
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/",
    # },{
        title: "MrLycorious",
        href: "http://www.wangzhui.site/"
        }
]

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 2ec70d0ec18d1abed9da       #生成的clientID
  clientSecret: be4cb5a22da1ee365494da52f87a5068e2c0746a  #生成的clientSecret
  repo:  talk   #仓库名称
  owner: zhuiwang   #github用户名
  admin: zhuiwang
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


## => Markdown Enhancements
##############################
## Mathjax
mathjax: true # false (default), true
mathjax_autoNumber: true # false (default), true

## Mermaid
mermaid: true # false (default), true

## Chart
chart: true # false (default), true

